ALTER TABLE erp_partner
  MODIFY COLUMN wecom_chat_id VARCHAR(100) DEFAULT NULL COMMENT '企业微信客户群ID',
  MODIFY COLUMN wecom_chat_name VARCHAR(200) DEFAULT NULL COMMENT '企业微信客户群名称',
  MODIFY COLUMN wecom_chat_owner VARCHAR(100) DEFAULT NULL COMMENT '企业微信客户群群主UserID';

ALTER TABLE erp_wecom_group COMMENT='企业微信客户群档案';
ALTER TABLE erp_wecom_group
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN chat_id VARCHAR(100) NOT NULL COMMENT '企业微信客户群ID',
  MODIFY COLUMN group_name VARCHAR(200) DEFAULT NULL COMMENT '客户群名称',
  MODIFY COLUMN owner VARCHAR(100) DEFAULT NULL COMMENT '群主UserID',
  MODIFY COLUMN group_status TINYINT DEFAULT 0 COMMENT '客户群状态：0正常 1跟进人离职 2离职继承中 3离职继承完成',
  MODIFY COLUMN member_count INT NOT NULL DEFAULT 0 COMMENT '群成员数量',
  MODIFY COLUMN group_create_time DATETIME DEFAULT NULL COMMENT '企业微信客户群创建时间',
  MODIFY COLUMN sync_time DATETIME DEFAULT NULL COMMENT '最近同步时间',
  MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE erp_ship_notice COMMENT='船期企业微信通知任务';
ALTER TABLE erp_ship_notice
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN presale_order_id BIGINT NOT NULL COMMENT '预销售单ID',
  MODIFY COLUMN partner_id BIGINT NOT NULL COMMENT '二批商往来单位ID',
  MODIFY COLUMN partner_name VARCHAR(200) DEFAULT NULL COMMENT '二批商名称',
  MODIFY COLUMN chat_id VARCHAR(100) DEFAULT NULL COMMENT '企业微信客户群ID',
  MODIFY COLUMN chat_name VARCHAR(200) DEFAULT NULL COMMENT '企业微信客户群名称',
  MODIFY COLUMN sender VARCHAR(100) DEFAULT NULL COMMENT '企业微信群发发送人UserID',
  MODIFY COLUMN contract_no VARCHAR(100) DEFAULT NULL COMMENT '合同号',
  MODIFY COLUMN container_no VARCHAR(100) DEFAULT NULL COMMENT '集装箱号',
  MODIFY COLUMN expected_arrival_date DATETIME DEFAULT NULL COMMENT '预计到港日期',
  MODIFY COLUMN content TEXT COMMENT '通知内容',
  MODIFY COLUMN wecom_msg_id VARCHAR(100) DEFAULT NULL COMMENT '企业微信群发任务ID',
  MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '通知状态：1已创建待成员确认 2已发送 9失败',
  MODIFY COLUMN error_message VARCHAR(500) DEFAULT NULL COMMENT '企业微信接口返回信息或错误原因',
  MODIFY COLUMN create_user_id BIGINT DEFAULT NULL COMMENT '创建人ID',
  MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
