ALTER TABLE `erp_partner`
  COMMENT = '往来单位表',
  MODIFY COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `partner_code` varchar(64) DEFAULT NULL COMMENT '往来单位编码',
  MODIFY COLUMN `partner_name` varchar(200) DEFAULT NULL COMMENT '往来单位名称',
  MODIFY COLUMN `partner_type` int(11) DEFAULT 1 COMMENT '单位类型 1-供应商 2-客户 3-供应商/客户',
  MODIFY COLUMN `business_role` varchar(128) DEFAULT NULL COMMENT '业务角色 BRAND-品牌方 FUNDER-资方 SECONDARY-二批主体 INTERNAL-鲜牧内部主体',
  MODIFY COLUMN `tax_no` varchar(100) DEFAULT NULL COMMENT '税号',
  MODIFY COLUMN `bank_name` varchar(200) DEFAULT NULL COMMENT '开户行',
  MODIFY COLUMN `bank_account` varchar(100) DEFAULT NULL COMMENT '银行账号',
  MODIFY COLUMN `address` varchar(255) DEFAULT NULL COMMENT '地址',
  MODIFY COLUMN `contact_name` varchar(64) DEFAULT NULL COMMENT '联系人',
  MODIFY COLUMN `contact_phone` varchar(64) DEFAULT NULL COMMENT '联系电话',
  MODIFY COLUMN `contact_email` varchar(128) DEFAULT NULL COMMENT '联系邮箱',
  MODIFY COLUMN `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `status` int(11) DEFAULT 1 COMMENT '状态 0-禁用 1-启用',
  MODIFY COLUMN `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  MODIFY COLUMN `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `erp_product`
  COMMENT = '产品档案表',
  MODIFY COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `product_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
  MODIFY COLUMN `alias_codes` varchar(255) DEFAULT NULL COMMENT '别名编码，多个以逗号分隔',
  MODIFY COLUMN `product_name` varchar(200) DEFAULT NULL COMMENT '产品中文名称',
  MODIFY COLUMN `product_name_en` varchar(255) DEFAULT NULL COMMENT '产品英文名称',
  MODIFY COLUMN `product_spec` varchar(200) DEFAULT NULL COMMENT '产品规格',
  MODIFY COLUMN `unit` varchar(32) DEFAULT NULL COMMENT '计量单位',
  MODIFY COLUMN `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌方主体ID',
  MODIFY COLUMN `brand` varchar(100) DEFAULT NULL COMMENT '品牌方名称',
  MODIFY COLUMN `origin_country` varchar(100) DEFAULT NULL COMMENT '原产国',
  MODIFY COLUMN `default_tax_rate` decimal(10,2) DEFAULT 0.00 COMMENT '默认税率',
  MODIFY COLUMN `safe_stock_boxes` decimal(18,2) DEFAULT NULL COMMENT '安全库存箱数',
  MODIFY COLUMN `freshness_warning_days` int(11) DEFAULT NULL COMMENT '保鲜预警天数',
  MODIFY COLUMN `status` int(11) DEFAULT 1 COMMENT '状态 0-禁用 1-启用',
  MODIFY COLUMN `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  MODIFY COLUMN `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `erp_presale_order`
  COMMENT = '预销售单主表',
  MODIFY COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `order_no` varchar(64) DEFAULT NULL COMMENT '预销售单号',
  MODIFY COLUMN `seller_contract_no` varchar(100) DEFAULT NULL COMMENT '卖方合同号',
  MODIFY COLUMN `customer_reference` varchar(200) DEFAULT NULL COMMENT '采购方',
  MODIFY COLUMN `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌方ID',
  MODIFY COLUMN `brand_name` varchar(200) DEFAULT NULL COMMENT '品牌方名称',
  MODIFY COLUMN `estimate_file_path` varchar(500) DEFAULT NULL COMMENT '预售销售单文件路径',
  MODIFY COLUMN `estimate_file_name` varchar(255) DEFAULT NULL COMMENT '预售销售单文件名',
  MODIFY COLUMN `estimate_raw_text` longtext COMMENT '预售销售单OCR原始文本',
  MODIFY COLUMN `currency` varchar(32) DEFAULT 'CNY' COMMENT '币种',
  MODIFY COLUMN `order_date` datetime DEFAULT NULL COMMENT '下单日期',
  MODIFY COLUMN `expected_date` datetime DEFAULT NULL COMMENT '预计到港日期',
  MODIFY COLUMN `status` int(11) DEFAULT 0 COMMENT '状态 0-草稿 1-已保存',
  MODIFY COLUMN `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  MODIFY COLUMN `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `erp_presale_order_item`
  COMMENT = '预销售单明细表',
  MODIFY COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `presale_order_id` bigint(20) DEFAULT NULL COMMENT '预销售单ID',
  MODIFY COLUMN `line_no` int(11) DEFAULT NULL COMMENT '行号',
  MODIFY COLUMN `product_id` bigint(20) DEFAULT NULL COMMENT '产品ID',
  MODIFY COLUMN `product_code` varchar(64) DEFAULT NULL COMMENT '系统产品编码',
  MODIFY COLUMN `source_product_code` varchar(64) DEFAULT NULL COMMENT '单据原始产品编码',
  MODIFY COLUMN `product_name` varchar(200) DEFAULT NULL COMMENT '产品中文名称',
  MODIFY COLUMN `product_name_en` varchar(500) DEFAULT NULL COMMENT '产品英文名称',
  MODIFY COLUMN `quantity_ton` decimal(18,4) DEFAULT 0.0000 COMMENT '数量(吨)',
  MODIFY COLUMN `quantity_kg` decimal(18,2) DEFAULT 0.00 COMMENT '数量(KG)',
  MODIFY COLUMN `price_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '单价',
  MODIFY COLUMN `price_currency` varchar(32) DEFAULT 'CNY' COMMENT '单价币种',
  MODIFY COLUMN `price_unit` varchar(32) DEFAULT 'KG' COMMENT '单价单位',
  MODIFY COLUMN `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `erp_presale_confirm`
  COMMENT = '客户订单确认函主表',
  MODIFY COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `presale_order_id` bigint(20) DEFAULT NULL COMMENT '预销售单ID',
  MODIFY COLUMN `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌方ID',
  MODIFY COLUMN `brand_name` varchar(200) DEFAULT NULL COMMENT '品牌方名称',
  MODIFY COLUMN `buyer_partner_id` bigint(20) DEFAULT NULL COMMENT '采购方ID',
  MODIFY COLUMN `buyer_partner_name` varchar(200) DEFAULT NULL COMMENT '采购方名称',
  MODIFY COLUMN `buyer_partner_role` varchar(128) DEFAULT NULL COMMENT '采购方角色',
  MODIFY COLUMN `contract_no` varchar(100) DEFAULT NULL COMMENT '合同号',
  MODIFY COLUMN `container_no` varchar(100) DEFAULT NULL COMMENT '集装箱号',
  MODIFY COLUMN `expected_arrival_date` datetime DEFAULT NULL COMMENT '预计到港日期',
  MODIFY COLUMN `total_amount` decimal(18,2) DEFAULT 0.00 COMMENT '总金额(CNY)',
  MODIFY COLUMN `currency` varchar(32) DEFAULT 'CNY' COMMENT '币种',
  MODIFY COLUMN `file_path` varchar(500) DEFAULT NULL COMMENT '客户订单确认函文件路径',
  MODIFY COLUMN `file_name` varchar(255) DEFAULT NULL COMMENT '客户订单确认函文件名',
  MODIFY COLUMN `raw_text` longtext COMMENT '客户订单确认函OCR原始文本',
  MODIFY COLUMN `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  MODIFY COLUMN `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `erp_presale_confirm_item`
  COMMENT = '客户订单确认函明细表',
  MODIFY COLUMN `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `confirm_id` bigint(20) DEFAULT NULL COMMENT '客户订单确认函ID',
  MODIFY COLUMN `line_no` int(11) DEFAULT NULL COMMENT '行号',
  MODIFY COLUMN `product_id` bigint(20) DEFAULT NULL COMMENT '产品ID',
  MODIFY COLUMN `product_code` varchar(64) DEFAULT NULL COMMENT '系统产品编码',
  MODIFY COLUMN `source_product_code` varchar(64) DEFAULT NULL COMMENT '单据原始产品编码',
  MODIFY COLUMN `product_name` varchar(200) DEFAULT NULL COMMENT '产品中文名称',
  MODIFY COLUMN `product_name_en` varchar(500) DEFAULT NULL COMMENT '产品英文名称',
  MODIFY COLUMN `unit` varchar(32) DEFAULT NULL COMMENT '计量单位',
  MODIFY COLUMN `quantity` decimal(18,2) DEFAULT 0.00 COMMENT '数量',
  MODIFY COLUMN `unit_price_incl_tax` decimal(18,4) DEFAULT 0.0000 COMMENT '单价(含税)',
  MODIFY COLUMN `line_total_incl_tax` decimal(18,2) DEFAULT 0.00 COMMENT '总值(含税)',
  MODIFY COLUMN `tax_rate` decimal(10,2) DEFAULT 9.00 COMMENT '税率',
  MODIFY COLUMN `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime DEFAULT NULL COMMENT '更新时间';
